### ISSUE TITLE
Trained model weights for the proposed and baseline methods

### ISSUE THREAD

**Issue by Depanshu-Sani** [ltong1130ztr/HAFrame#1]
Dear authors,
Can you also provide the weights for all (or some) models you used in the experiments?

**Comment by ltong1130ztr** [comment]
Hi, thanks for your interest! Unfortunately, we ran our experiments completely on cloud service, and I only have evaluation results downloaded for my local storage. I vaguely remember that all checkpoints in my experiments (comparison + ablation + neural-collapse viz) are about 180 GB to 200 GB, in case you want to run the scripts and generate them yourself.
